// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxProApi.Data;

#nullable disable

namespace TaxProApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924072439_AddWorkflowStateTracking")]
    partial class AddWorkflowStateTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaxProApi.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("TaxProApi.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientCompany")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TimeSlot")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingReference")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("TaxProApi.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("ReadTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("TaxProApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NTN")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TaxProApi.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClientCompany")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClientEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsultationReference")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ConsultationType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TimeSlot")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ConsultationReference")
                        .IsUnique();

                    b.HasIndex("ServiceId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("TaxProApi.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Online consultations are PKR 5,000 and private face-to-face consultations are PKR 7,000. Payment must be made in advance via bank transfer or Raast.",
                            Category = "Payments",
                            CreatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 298, DateTimeKind.Utc).AddTicks(4097),
                            IsActive = true,
                            Question = "What is the advance consultation fee?",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Answer = "After bank transfer, provide the transaction reference number. Our team verifies it within 2-4 hours during business hours.",
                            Category = "Payments",
                            CreatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 300, DateTimeKind.Utc).AddTicks(778),
                            IsActive = true,
                            Question = "How do I verify my payment?",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Answer = "No. For confidentiality and security, private meeting location details are only shared with confirmed clients after payment verification.",
                            Category = "Privacy",
                            CreatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 300, DateTimeKind.Utc).AddTicks(793),
                            IsActive = true,
                            Question = "Is the meeting location publicly available?",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Standard consultations are 1 hour. Complex matters may require additional sessions at the same rate.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 300, DateTimeKind.Utc).AddTicks(798),
                            IsActive = true,
                            Question = "How long does a consultation session last?",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("TaxProApi.Models.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("BusinessType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InquiryReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ServiceInterest")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("InquiryReference")
                        .IsUnique();

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("TaxProApi.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ConsultationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ProofFileName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProofFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RejectedByAdminId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VerifiedByAdminId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.HasIndex("PaymentReference")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TaxProApi.Models.PaymentSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("PaymentSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bank name for payments",
                            IsActive = true,
                            Key = "bank_name",
                            UpdatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 289, DateTimeKind.Utc).AddTicks(3435),
                            Value = "Meezan Bank Ltd"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Account holder name",
                            IsActive = true,
                            Key = "account_title",
                            UpdatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 290, DateTimeKind.Utc).AddTicks(2978),
                            Value = "TaxPro Consultants"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bank account number",
                            IsActive = true,
                            Key = "account_number",
                            UpdatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 290, DateTimeKind.Utc).AddTicks(2987),
                            Value = "01230123456789"
                        },
                        new
                        {
                            Id = 4,
                            Description = "IBAN for transfers",
                            IsActive = true,
                            Key = "iban",
                            UpdatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 290, DateTimeKind.Utc).AddTicks(2992),
                            Value = "PK36MEZN0001230123456789"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bank branch code",
                            IsActive = true,
                            Key = "branch_code",
                            UpdatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 290, DateTimeKind.Utc).AddTicks(2996),
                            Value = "0123"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Raast ID / Mobile number",
                            IsActive = true,
                            Key = "raast_id",
                            UpdatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 290, DateTimeKind.Utc).AddTicks(3000),
                            Value = "03001234567"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Online consultation fee (PKR)",
                            IsActive = true,
                            Key = "consultation_fee_online",
                            UpdatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 290, DateTimeKind.Utc).AddTicks(3004),
                            Value = "5000"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Face-to-face consultation fee (PKR)",
                            IsActive = true,
                            Key = "consultation_fee_f2f",
                            UpdatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 290, DateTimeKind.Utc).AddTicks(3009),
                            Value = "7000"
                        });
                });

            modelBuilder.Entity("TaxProApi.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("AppointmentDetails")
                        .HasColumnType("text");

                    b.Property<string>("ClientCompany")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClientEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ConsultationId")
                        .HasColumnType("integer");

                    b.Property<string>("ConsultationMode")
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PdfFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("TaxProApi.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 294, DateTimeKind.Utc).AddTicks(4971),
                            Description = "Individual & corporate return filing",
                            Icon = "account_balance",
                            IsActive = true,
                            Name = "Income Tax Advisory & Filing",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 297, DateTimeKind.Utc).AddTicks(3687),
                            Description = "FBR Federal Sales Tax & provincial GST registrations",
                            Icon = "receipt",
                            IsActive = true,
                            Name = "Sales Tax & GST",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 297, DateTimeKind.Utc).AddTicks(3721),
                            Description = "Continuous WHT monitoring and e-filing",
                            Icon = "price_change",
                            IsActive = true,
                            Name = "Withholding Tax (WHT)",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 297, DateTimeKind.Utc).AddTicks(3729),
                            Description = "NTN registration, Iris portal compliance",
                            Icon = "verified",
                            IsActive = true,
                            Name = "FBR Services & Notice Defense",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 297, DateTimeKind.Utc).AddTicks(3737),
                            Description = "Sindh Revenue Board and PRA compliance",
                            Icon = "location_city",
                            IsActive = true,
                            Name = "SRB & Provincial Services",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 297, DateTimeKind.Utc).AddTicks(3745),
                            Description = "SECP company incorporation and filings",
                            Icon = "corporate_fare",
                            IsActive = true,
                            Name = "Corporate Tax & SECP",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 297, DateTimeKind.Utc).AddTicks(3753),
                            Description = "Audit defense and appeal representation",
                            Icon = "gavel",
                            IsActive = true,
                            Name = "Tax Assessment & Appeals",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 24, 7, 24, 30, 297, DateTimeKind.Utc).AddTicks(3760),
                            Description = "Fiscal architecture and tax optimization",
                            Icon = "trending_up",
                            IsActive = true,
                            Name = "Strategic Business Restructuring",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("TaxProApi.Models.TaxRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxIncome")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MinIncome")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(8,6)");

                    b.Property<string>("Statute")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TaxYear")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TaxRules");
                });

            modelBuilder.Entity("TaxProApi.Models.Appointment", b =>
                {
                    b.HasOne("TaxProApi.Models.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaxProApi.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Client");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TaxProApi.Models.Consultation", b =>
                {
                    b.HasOne("TaxProApi.Models.Client", "Client")
                        .WithMany("Consultations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaxProApi.Models.Service", "Service")
                        .WithMany("Consultations")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Client");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TaxProApi.Models.Inquiry", b =>
                {
                    b.HasOne("TaxProApi.Models.Client", "Client")
                        .WithMany("Inquiries")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TaxProApi.Models.Payment", b =>
                {
                    b.HasOne("TaxProApi.Models.Consultation", "Consultation")
                        .WithOne("Payment")
                        .HasForeignKey("TaxProApi.Models.Payment", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("TaxProApi.Models.Receipt", b =>
                {
                    b.HasOne("TaxProApi.Models.Consultation", "Consultation")
                        .WithOne("Receipt")
                        .HasForeignKey("TaxProApi.Models.Receipt", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxProApi.Models.Payment", "Payment")
                        .WithOne("Receipt")
                        .HasForeignKey("TaxProApi.Models.Receipt", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("TaxProApi.Models.Client", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Consultations");

                    b.Navigation("Inquiries");
                });

            modelBuilder.Entity("TaxProApi.Models.Consultation", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("TaxProApi.Models.Payment", b =>
                {
                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("TaxProApi.Models.Service", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Consultations");
                });
#pragma warning restore 612, 618
        }
    }
}
