// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxProApi.Data;

#nullable disable

namespace TaxProApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: This is a simplified snapshot. In production, run: dotnet ef migrations add Initial
            // This file will be auto-generated with complete schema details.
            
            modelBuilder.Entity("TaxProApi.Models.AdminUser", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd();
                b.Property<string>("Username").IsRequired().HasMaxLength(100);
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500);
                b.Property<string>("Email").HasMaxLength(200);
                b.Property<bool>("IsActive");
                b.Property<DateTime>("CreatedAt");
                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.ToTable("AdminUsers");
            });

            modelBuilder.Entity("TaxProApi.Models.Consultation", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd();
                b.Property<string>("ConsultationReference").IsRequired().HasMaxLength(60);
                b.Property<int?>("ClientId");
                b.Property<int?>("ServiceId");
                b.Property<int>("Mode");
                b.Property<string>("ConsultationType").IsRequired().HasMaxLength(200);
                b.Property<string>("Description").HasMaxLength(2000);
                b.Property<DateTime>("AppointmentDate");
                b.Property<string>("TimeSlot").HasMaxLength(100);
                b.Property<string>("ClientName").IsRequired().HasMaxLength(150);
                b.Property<string>("ClientPhone").HasMaxLength(30);
                b.Property<string>("ClientEmail").HasMaxLength(200);
                b.Property<string>("ClientCompany").HasMaxLength(200);
                b.Property<int>("Status");
                b.Property<string>("AdminNotes").HasMaxLength(500);
                b.Property<string>("CancellationReason").HasMaxLength(500);
                b.Property<DateTime>("CreatedAt");
                b.Property<DateTime?>("UpdatedAt");
                b.Property<DateTime?>("ConfirmedAt");
                b.Property<DateTime?>("CancelledAt");
                b.HasKey("Id");
                b.HasIndex("ConsultationReference").IsUnique();
                b.ToTable("Consultations");
            });

            modelBuilder.Entity("TaxProApi.Models.Payment", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd();
                b.Property<string>("PaymentReference").IsRequired().HasMaxLength(60);
                b.Property<int>("ConsultationId");
                b.Property<decimal>("Amount").HasColumnType("numeric(18,2)");
                b.Property<int>("Method");
                b.Property<string>("TransactionReference").HasMaxLength(200);
                b.Property<DateTime?>("PaymentDate");
                b.Property<string>("ProofFilePath").HasMaxLength(500);
                b.Property<string>("ProofFileName").HasMaxLength(100);
                b.Property<int>("Status");
                b.Property<string>("AdminRemarks").HasMaxLength(500);
                b.Property<DateTime?>("VerifiedAt");
                b.Property<int?>("VerifiedByAdminId");
                b.Property<DateTime?>("RejectedAt");
                b.Property<int?>("RejectedByAdminId");
                b.Property<DateTime>("CreatedAt");
                b.Property<DateTime?>("UpdatedAt");
                b.HasKey("Id");
                b.HasIndex("PaymentReference").IsUnique();
                b.ToTable("Payments");
            });

            modelBuilder.Entity("TaxProApi.Models.Receipt", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd();
                b.Property<string>("ReceiptNumber").IsRequired().HasMaxLength(60);
                b.Property<int>("ConsultationId");
                b.Property<int>("PaymentId");
                b.Property<string>("ClientName").IsRequired().HasMaxLength(150);
                b.Property<string>("ClientEmail").HasMaxLength(200);
                b.Property<string>("ClientPhone").HasMaxLength(30);
                b.Property<string>("ClientCompany").HasMaxLength(200);
                b.Property<string>("ServiceDescription").IsRequired().HasMaxLength(200);
                b.Property<decimal>("Amount").HasColumnType("numeric(18,2)");
                b.Property<string>("PaymentMethod").HasMaxLength(100);
                b.Property<string>("TransactionReference").HasMaxLength(200);
                b.Property<DateTime>("IssuedAt");
                b.Property<string>("PdfFilePath").HasMaxLength(500);
                b.Property<string>("ConsultationMode");
                b.Property<string>("AppointmentDetails");
                b.HasKey("Id");
                b.HasIndex("ReceiptNumber").IsUnique();
                b.ToTable("Receipts");
            });

            // Additional entities (simplified for brevity)
            // Full snapshot would include: Client, Service, Appointment, Inquiry, FAQ, BlogPost, TaxRule, PaymentSetting

#pragma warning restore 612, 618
        }
    }
}
